package rhinemod.util;

import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.megacrit.cardcrawl.helpers.ImageMaster;

public class RhineImageMaster {
    public static Texture cursor1;
    public static Texture cursor2;
    public static Texture topPanelBase;
    public static Texture topPanelTimer;
    public static Texture topPanelKeyBlue;
    public static Texture topPanelKeyRed;
    public static Texture topPanelKeyGreen;
    public static Texture topPanelHeart;
    public static Texture topPanelHeartWhite;
    public static Texture topPanelGold;
    public static Texture topPanelEndless;
    public static Texture topPanelFloor;
    public static Texture topPanelAscension;
    public static Texture topPanelMap;
    public static Texture topPanelDeck;
    public static Texture topPanelSettings;
    public static Texture endTurnButton;
    public static Texture endTurnButtonGlow;
    public static Texture endTurnButtonHover;
    public static Texture deckButton;
    public static Texture discardButton;
    public static Texture countCircle;
    public static Texture attackCommonL;
    public static Texture attackUncommonL;
    public static Texture attackRareL;
    public static Texture skillCommonL;
    public static Texture skillUncommonL;
    public static Texture skillRareL;
    public static Texture powerCommonL;
    public static Texture powerUncommonL;
    public static Texture powerRareL;
    public static Texture commonBannerL;
    public static Texture uncommonBannerL;
    public static Texture rareBannerL;
    public static Texture attackCommon;
    public static Texture attackUncommon;
    public static Texture attackRare;
    public static Texture skillCommon;
    public static Texture skillUncommon;
    public static Texture skillRare;
    public static Texture powerCommon;
    public static Texture powerUncommon;
    public static Texture powerRare;
    public static Texture commonBanner;
    public static Texture uncommonBanner;
    public static Texture rareBanner;
    public static Texture bossCardReward;
    public static Texture normalCardReward;
    public static Texture relicLink;
    public static Texture rewardListItemPanel;
    public static Texture rewardScreenSheet;
    public static Texture takeAll;
    public static Texture takeAllUsed;
    public static Texture selectBanner;
    public static Texture bannerRing;
    public static Texture bannerCircleL;
    public static Texture bannerCircleR;
    public static Texture bannerPointer;
    public static Texture potionBackground;
    public static Texture potionTop;
    public static Texture potionBottom;
    public static Texture potionSelectBox;
    public static Texture peekButton;
    public static Texture buttonL;
    public static Texture buttonLRed;
    public static Texture cancelButton;
    public static Texture cancelButtonOutline;
    public static Texture confirmButton;
    public static Texture confirmButtonOutline;
    public static Texture settingsBackground;
    public static Texture optionAbandon;
    public static Texture optionToggle;
    public static Texture optionToggleOn;
    public static Texture optionSliderBg;
    public static Texture optionSlider;
    public static Texture optionExit;
    public static Texture optionConfirm;
    public static Texture optionYes;
    public static Texture optionNo;
    public static Texture renameBox;
    public static Texture inputSettings;
    public static Texture proceedButton;
    public static Texture proceedButtonOutline;
    public static Texture reticleCorner;
    public static TextureAtlas.AtlasRegion singleFile;
    public static String circleLeft = "resources/rhinemod/images/ui/door/circle_left.png";
    public static String circleRight = "resources/rhinemod/images/ui/door/circle_right.png";
    public static String doorLeft = "resources/rhinemod/images/ui/door/door_left.png";
    public static String doorRight = "resources/rhinemod/images/ui/door/door_right.png";
    public static String glowBlue = "resources/rhinemod/images/ui/door/glow_blue.png";
    public static String glowGreen = "resources/rhinemod/images/ui/door/glow_green.png";
    public static String glowRed = "resources/rhinemod/images/ui/door/glow_red.png";
    public static String lockBlue = "resources/rhinemod/images/ui/door/lock_blue.png";
    public static String lockGreen = "resources/rhinemod/images/ui/door/lock_green.png";
    public static String lockRed = "resources/rhinemod/images/ui/door/lock_red.png";
    public static Texture checkBox;
    public static Texture tick;
    public static Texture popupArrow;
    public static Texture scrollBarHorizontalTrain;
    public static Texture scrollBarTrain;
    public static Texture scrollBarTrackHorizontalMid;
    public static Texture scrollBarTrackMid;
    public static Texture scrollBarTrackBottom;
    public static Texture scrollBarTrackLeft;
    public static Texture scrollBarTrackRight;
    public static Texture scrollBarTrackTop;
    public static Texture eventPanel;
    public static Texture eventEnabledButton;
    public static Texture eventDisabledButton;
    public static Texture eventTextPanel;
    public static Texture mapTop;
    public static Texture mapMid;
    public static Texture mapBot;
    public static Texture mapChest;
    public static Texture mapElite;
    public static Texture mapEvent;
    public static Texture mapMonster;
    public static Texture mapRest;
    public static Texture mapShop;
    public static Texture mapLegend;
    public static Texture mapOutline;
    public static Texture mapDot;
    public static Texture mapLine;
    public static Texture mapBlender;
    public static String blueKey = "resources/rhinemod/images/relics/blue_key.png";
    public static String greenKey = "resources/rhinemod/images/relics/green_key.png";
    public static String redKey = "resources/rhinemod/images/relics/red_key.png";
    public static Texture mapCircle5;
    public static Texture mainMenuBackground;

    public static void initialize() {
        cursor1 = ImageMaster.loadImage("resources/rhinemod/images/ui/cursors/gold2.png");
        cursor2 = ImageMaster.loadImage("resources/rhinemod/images/ui/cursors/magGlass2.png");

        topPanelBase = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/bar.png");
        topPanelTimer = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/timer.png");
        topPanelKeyBlue = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/key_blue.png");
        topPanelKeyRed = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/key_red.png");
        topPanelKeyGreen = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/key_green.png");
        topPanelHeart = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/panelHeart.png");
        topPanelHeartWhite = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/panel_heart_white.png");
        topPanelGold = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/gold.png");
        topPanelEndless = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/endless.png");
        topPanelFloor = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/floor.png");
        topPanelAscension = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/ascension.png");
        topPanelMap = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/map.png");
        topPanelDeck = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/deck.png");
        topPanelSettings = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/settings.png");

        endTurnButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/endTurnButton.png");
        endTurnButtonGlow = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/endTurnButtonGlow.png");
        endTurnButtonHover = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/endTurnButtonHover.png");

        deckButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/deckButton.png");
        discardButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/discardButton.png");
        countCircle = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/countCircle.png");

        attackCommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/attack_common.png");
        attackUncommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/attack_uncommon.png");
        attackRareL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/attack_rare.png");
        skillCommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/skill_common.png");
        skillUncommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/skill_uncommon.png");
        skillRareL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/skill_rare.png");
        powerCommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/power_common.png");
        powerUncommonL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/power_uncommon.png");
        powerRareL = ImageMaster.loadImage("resources/rhinemod/images/1024/frame/power_rare.png");
        commonBannerL = ImageMaster.loadImage("resources/rhinemod/images/1024/banner/common.png");
        uncommonBannerL = ImageMaster.loadImage("resources/rhinemod/images/1024/banner/uncommon.png");
        rareBannerL = ImageMaster.loadImage("resources/rhinemod/images/1024/banner/rare.png");

        attackCommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/attack_common.png");
        attackUncommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/attack_uncommon.png");
        attackRare = ImageMaster.loadImage("resources/rhinemod/images/512/frame/attack_rare.png");
        skillCommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/skill_common.png");
        skillUncommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/skill_uncommon.png");
        skillRare = ImageMaster.loadImage("resources/rhinemod/images/512/frame/skill_rare.png");
        powerCommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/power_common.png");
        powerUncommon = ImageMaster.loadImage("resources/rhinemod/images/512/frame/power_uncommon.png");
        powerRare = ImageMaster.loadImage("resources/rhinemod/images/512/frame/power_rare.png");
        commonBanner = ImageMaster.loadImage("resources/rhinemod/images/512/banner/common.png");
        uncommonBanner = ImageMaster.loadImage("resources/rhinemod/images/512/banner/uncommon.png");
        rareBanner = ImageMaster.loadImage("resources/rhinemod/images/512/banner/rare.png");

        bossCardReward = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/bossCardReward.png");
        normalCardReward = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/normalCardReward.png");
        relicLink = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/relic_link.png");
        rewardListItemPanel = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/rewardListItemPanel.png");
        rewardScreenSheet = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/rewardScreenSheet.png");
        takeAll = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/takeAll.png");
        takeAllUsed = ImageMaster.loadImage("resources/rhinemod/images/ui/reward/takeAllUsed.png");

        selectBanner = ImageMaster.loadImage("resources/rhinemod/images/ui/selectBanner/background.png");
        bannerRing = ImageMaster.loadImage("resources/rhinemod/images/ui/selectBanner/ring.png");
        bannerCircleL = ImageMaster.loadImage("resources/rhinemod/images/ui/selectBanner/circleL.png");
        bannerCircleR = ImageMaster.loadImage("resources/rhinemod/images/ui/selectBanner/circleR.png");
        bannerPointer = ImageMaster.loadImage("resources/rhinemod/images/ui/selectBanner/pointer.png");

        potionBackground = ImageMaster.loadImage("resources/rhinemod/images/ui/potionPopUp/bg.png");
        potionTop = ImageMaster.loadImage("resources/rhinemod/images/ui/potionPopUp/top.png");
        potionBottom = ImageMaster.loadImage("resources/rhinemod/images/ui/potionPopUp/bot.png");
        potionSelectBox = ImageMaster.loadImage("resources/rhinemod/images/ui/potionPopUp/potionSelectBox.png");

        peekButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/peek_button.png");
        buttonL = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/buttonL.png");
        buttonLRed = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/buttonLRed.png");
        cancelButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/cancelButton.png");
        cancelButtonOutline = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/cancelButtonOutline.png");
        confirmButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/confirmButton.png");
        confirmButtonOutline = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/confirmButtonOutline.png");

        settingsBackground = ImageMaster.loadImage("resources/rhinemod/images/ui/option/settingsBackground.png");
        optionAbandon = ImageMaster.loadImage("resources/rhinemod/images/ui/option/abandon.png");
        optionToggle = ImageMaster.loadImage("resources/rhinemod/images/ui/option/toggleButtonBase.png");
        optionToggleOn = ImageMaster.loadImage("resources/rhinemod/images/ui/option/toggleButtonOverlay2.png");
        optionSliderBg = ImageMaster.loadImage("resources/rhinemod/images/ui/option/sliderBg.png");
        optionSlider = ImageMaster.loadImage("resources/rhinemod/images/ui/option/slider.png");
        optionExit = ImageMaster.loadImage("resources/rhinemod/images/ui/option/quitButton.png");
        optionConfirm = ImageMaster.loadImage("resources/rhinemod/images/ui/option/confirm.png");
        optionYes = ImageMaster.loadImage("resources/rhinemod/images/ui/option/yes.png");
        optionNo = ImageMaster.loadImage("resources/rhinemod/images/ui/option/no.png");
        renameBox = ImageMaster.loadImage("resources/rhinemod/images/ui/option/nameBox.png");
        inputSettings = ImageMaster.loadImage("resources/rhinemod/images/ui/option/inputPanelBg.png");

        proceedButton = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/proceedButton.png");
        proceedButtonOutline = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/proceedButtonOutline.png");

        reticleCorner = ImageMaster.loadImage("resources/rhinemod/images/ui/combat/reticleCorner.png");
        singleFile = new TextureAtlas.AtlasRegion(ImageMaster.loadImage("resources/rhinemod/images/ui/combat/singleFile.png"), 0, 0, 500, 500);

        checkBox = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/checkbox.png");
        tick = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/tick.png");
        popupArrow = ImageMaster.loadImage("resources/rhinemod/images/ui/topPanel/popupArrow.png");

        scrollBarHorizontalTrain = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarHorizontalTrain.png");
        scrollBarTrain = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrain.png");
        scrollBarTrackHorizontalMid = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackHorizontalMid.png");
        scrollBarTrackMid = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackMid.png");
        scrollBarTrackBottom = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackBottom.png");
        scrollBarTrackLeft = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackLeft.png");
        scrollBarTrackRight = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackRight.png");
        scrollBarTrackTop = ImageMaster.loadImage("resources/rhinemod/images/ui/scrollBar/scrollBarTrackTop.png");

        eventPanel = ImageMaster.loadImage("resources/rhinemod/images/ui/event/panel.png");
        eventEnabledButton = ImageMaster.loadImage("resources/rhinemod/images/ui/event/enabledButton.png");
        eventDisabledButton = ImageMaster.loadImage("resources/rhinemod/images/ui/event/disabledButton.png");
        eventTextPanel = ImageMaster.loadImage("resources/rhinemod/images/ui/event/roomTextPanel.png");

        mapTop = ImageMaster.loadImage("resources/rhinemod/images/ui/map/mapTop.png");
        mapMid = ImageMaster.loadImage("resources/rhinemod/images/ui/map/mapMid.png");
        mapBot = ImageMaster.loadImage("resources/rhinemod/images/ui/map/mapBot.png");
        mapChest = ImageMaster.loadImage("resources/rhinemod/images/ui/map/chest.png");
        mapElite = ImageMaster.loadImage("resources/rhinemod/images/ui/map/elite.png");
        mapEvent = ImageMaster.loadImage("resources/rhinemod/images/ui/map/event.png");
        mapMonster = ImageMaster.loadImage("resources/rhinemod/images/ui/map/monster.png");
        mapRest = ImageMaster.loadImage("resources/rhinemod/images/ui/map/rest.png");
        mapShop = ImageMaster.loadImage("resources/rhinemod/images/ui/map/shop.png");
        mapOutline = ImageMaster.loadImage("resources/rhinemod/images/ui/map/outline.png");
        mapLegend = ImageMaster.loadImage("resources/rhinemod/images/ui/map/legend2.png");
        mapDot = ImageMaster.loadImage("resources/rhinemod/images/ui/map/dot.png");
        mapLine = ImageMaster.loadImage("resources/rhinemod/images/ui/map/line.png");
        mapBlender = ImageMaster.loadImage("resources/rhinemod/images/ui/map/mapBlend.png");
        mapCircle5 = ImageMaster.loadImage("resources/rhinemod/images/ui/map/circle5.png");

        mainMenuBackground = ImageMaster.loadImage("resources/rhinemod/images/ui/mainMenuBackground.png");
    }
}
